// Parses coverage/lcov.info, prints a per-file summary sorted worst-first,
// and fails when total line coverage drops below a floor.
//
//   dart tool/check_coverage.dart                 # default floor
//   dart tool/check_coverage.dart --min 80        # custom floor
//   dart tool/check_coverage.dart --lcov path.info
//
// Generated files are excluded so a `flutterfire configure` run cannot move
// the number on its own.

import 'dart:io';

/// Total line-coverage floor, in percent. Raise this as coverage improves —
/// never lower it to make a red build green.
const double defaultMinimum = 74.0;

/// Paths (matched as prefixes, repo-relative) excluded from the total.
const List<String> excludedPrefixes = <String>[
  'lib/firebase_options.dart', // generated by `flutterfire configure`
  'lib/dev/', // dev-only entrypoints, not shipped
];

void main(List<String> args) {
  final options = _parseArgs(args);
  final lcov = File(options.lcovPath);
  if (!lcov.existsSync()) {
    stderr.writeln(
      'No coverage file at ${options.lcovPath}. '
      'Run `flutter test --coverage` first.',
    );
    exit(2);
  }

  final files = _parseLcov(lcov.readAsLinesSync());
  final included = files.where((f) => !_isExcluded(f.path)).toList()
    ..sort((a, b) => a.percent.compareTo(b.percent));

  if (included.isEmpty) {
    stderr.writeln('No covered files found in ${options.lcovPath}.');
    exit(2);
  }

  final hit = included.fold<int>(0, (sum, f) => sum + f.linesHit);
  final found = included.fold<int>(0, (sum, f) => sum + f.linesFound);
  final total = found == 0 ? 0.0 : 100 * hit / found;

  stdout.writeln('Line coverage by file (worst first):');
  for (final file in included) {
    stdout.writeln(
      '  ${file.percent.toStringAsFixed(1).padLeft(5)}%  '
      '${file.linesHit.toString().padLeft(4)}/'
      '${file.linesFound.toString().padRight(4)}  ${file.path}',
    );
  }

  final excluded = files.where((f) => _isExcluded(f.path)).toList();
  if (excluded.isNotEmpty) {
    stdout.writeln('Excluded: ${excluded.map((f) => f.path).join(', ')}');
  }

  stdout.writeln(
    'TOTAL ${total.toStringAsFixed(2)}% ($hit/$found lines) '
    '— floor ${options.minimum.toStringAsFixed(1)}%',
  );

  _writeStepSummary(total, options.minimum, hit, found);

  if (total + 1e-9 < options.minimum) {
    stderr.writeln(
      'FAIL: line coverage ${total.toStringAsFixed(2)}% is below the '
      '${options.minimum.toStringAsFixed(1)}% floor.',
    );
    exit(1);
  }
  stdout.writeln('OK');
}

bool _isExcluded(String path) =>
    excludedPrefixes.any((prefix) => path.startsWith(prefix));

/// Appends a one-line verdict to the GitHub Actions job summary when running
/// in CI. No-op locally.
void _writeStepSummary(double total, double minimum, int hit, int found) {
  final summaryPath = Platform.environment['GITHUB_STEP_SUMMARY'];
  if (summaryPath == null || summaryPath.isEmpty) return;
  final verdict = total + 1e-9 < minimum ? '❌' : '✅';
  File(summaryPath).writeAsStringSync(
    '$verdict **Line coverage ${total.toStringAsFixed(2)}%** '
    '($hit/$found lines, floor ${minimum.toStringAsFixed(1)}%)\n',
    mode: FileMode.append,
  );
}

class _FileCoverage {
  _FileCoverage(this.path, this.linesFound, this.linesHit);

  final String path;
  final int linesFound;
  final int linesHit;

  double get percent => linesFound == 0 ? 100.0 : 100 * linesHit / linesFound;
}

List<_FileCoverage> _parseLcov(List<String> lines) {
  final result = <_FileCoverage>[];
  String? path;
  var found = 0;
  var hit = 0;
  for (final line in lines) {
    if (line.startsWith('SF:')) {
      path = line.substring(3).trim();
      found = 0;
      hit = 0;
    } else if (line.startsWith('LF:')) {
      found = int.tryParse(line.substring(3).trim()) ?? 0;
    } else if (line.startsWith('LH:')) {
      hit = int.tryParse(line.substring(3).trim()) ?? 0;
    } else if (line.trim() == 'end_of_record' && path != null) {
      result.add(_FileCoverage(path, found, hit));
      path = null;
    }
  }
  return result;
}

class _Options {
  _Options(this.lcovPath, this.minimum);

  final String lcovPath;
  final double minimum;
}

_Options _parseArgs(List<String> args) {
  var lcovPath = 'coverage/lcov.info';
  var minimum = defaultMinimum;
  for (var i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--min':
        minimum = double.tryParse(_requireValue(args, ++i, '--min')) ?? minimum;
      case '--lcov':
        lcovPath = _requireValue(args, ++i, '--lcov');
      default:
        stderr.writeln('Unknown argument: ${args[i]}');
        exit(64);
    }
  }
  return _Options(lcovPath, minimum);
}

String _requireValue(List<String> args, int index, String flag) {
  if (index >= args.length) {
    stderr.writeln('$flag requires a value.');
    exit(64);
  }
  return args[index];
}
